#!/bin/bash

# function to display progress bar
progress_bar() {
    local width=50
    local perc=$1
    local fill=$(printf "%${perc}s" | tr ' ' '=')
    local empty=$(printf "%$((width - perc))s")
    printf "[%-100s] %d%%\r" "$fill" "$perc"
}

progress_bar_movement() {
    while true; do
        if ! ps -p $! &>/dev/null; then
            break
        fi
        for i in {1..100}; do
            progress_bar $((i * 1))
            sleep $1
        done
    done
    progress_bar 100
}

validate_tfinstall() {
    if ! command -v terraform &>/dev/null; then
        echo "🤣 Using Terraform without installing terraform"
        exit 1
    fi
}
validate_tfinstall

terraform_init() {
    echo "Running Terraform init"
    {
        terraform init &>/dev/null
    }
}
terraform_init

terraform_plan() {
    echo "Running Terraform Plan"
    {
        terraform plan -out main.tfplan -var-file secret.tfvars
    } &>/dev/null &

    progress_bar_movement 0.43

    echo -e "\n✅ Terraform plan completed"
}
terraform_plan

terraform_apply() {
    echo "Running Terraform apply..."
    {
        terraform apply main.tfplan
    } &>/dev/null &

    progress_bar_movement 5
    echo -e "\n✅ Terraform apply complete."

}
terraform apply
