#!/bin/bash

source $HOME/Desktop/terraform-azure-aksacr/scripts/progress_bar.sh || exit 1

source $HOME/Desktop/terraform-azure-aksacr/scripts/alert.sh || exit 1


state_check() {
    if [ -f "terraform.tfstate" ]; then
        echo "State file found"
    else
        echo "State file not found"
        exit 1
    fi
}

destroy_aks() {

    echo "Checking if state file exists..."
    state_check
    echo "Starting terraform destroy...."
    {
        terraform destroy --auto-approve -var-file=personalenv.tfvars > /dev/null
    } &
    progress_bar_movement 5
    echo -e "\n✅ Terraform destroy complete."
    send_alert "AKS has been deleted ❌"
}
#destroy_aks
