#!/bin/bash

source ./progress_bar.sh

source ./alert.sh

cd ..

state_check() {
    if [ -f "terraform.tfstate" ]; then
        echo "State file found"
    else
        echo "State file not found"
        exit 1
    fi
}

destroy_aks() {
    echo "Checking if state file exists..."
    state_check
    echo "Starting terraform destroy...."
    {
        terraform destroy --auto-approve -var-file=secret.tfvars > /dev/null
    } &
    progress_bar_movement 5
    echo -e "\n✅ Terraform destroy complete."
    send_alert "AKS has been deleted ❌"
}
destroy_aks
